version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: gorent
      POSTGRES_PASSWORD: gorentpass
      POSTGRES_DB: gorent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gorent"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: